services:
  mysql:
    image: mysql:8.0
    container_name: shopping-live-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shopping_live
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
       resources:
         limits:
           cpus: '2'
           memory: 4G
         reservations:
           cpus: '2'
           memory: 4G

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shopping-live-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shopping_live
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      mysql:
        condition: service_healthy
#    restart: unless-stopped
    deploy:
       resources:
         limits:
           cpus: '2'
           memory: 4G
         reservations:
           cpus: '2'
           memory: 4G

  artillery:
    build:
      context: .
      dockerfile: artillery.Dockerfile
    container_name: artillery-load-test
    depends_on:
      backend:
        condition: service_started
    profiles:
      - test

  prometheus:
    image: prom/prometheus:latest
    container_name: shopping-live-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./backend/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus-local.yml'
      - '--storage.tsdb.path=/prometheus'
#      - '--storage.tsdb.retention.time=200h'
#      - '--web.enable-lifecycle'
#    restart: unless-stopped
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: shopping-live-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./backend/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./backend/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
#    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: shopping-live-loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
#    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: shopping-live-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc' # 호스트의 프로세스 정보 접근
      - '--path.rootfs=/rootfs' # 호스트의 루트 파일시스템 접근
      - '--path.sysfs=/host/sys' # 호스트의 시스템 정보 접근
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' # 불필요한 마운트 포인트 제외
      - '--collector.systemd' # systemd 메트릭 수집
      - '--collector.processes' # 프로세스 메트릭 수집

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:
  loki_data: