services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shopping-live-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.0.48:3306/shopping_live
      - SPRING_DATASOURCE_PASSWORD=1234

  node-exporter:
    image: prom/node-exporter:latest
    container_name: shopping-live-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc' # 호스트의 프로세스 정보 접근
      - '--path.rootfs=/rootfs' # 호스트의 루트 파일시스템 접근
      - '--path.sysfs=/host/sys' # 호스트의 시스템 정보 접근
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' # 불필요한 마운트 포인트 제외
      - '--collector.systemd' # systemd 메트릭 수집
      - '--collector.processes' # 프로세스 메트릭 수집

volumes: