events {
    worker_connections 1024;
}

http {
    # gzip 압축 설정
    gzip on;
    gzip_comp_level 9;
    gzip_vary on;
    gzip_types text/plain text/css application/json application/x-javascript application/javascript text/xml application/xml application/rss+xml text/javascript image/svg+xml application/vnd.ms-fontobject application/x-font-ttf font/opentype;

    include /etc/nginx/conf.d/*.conf;
}
