global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'spring-boot-app-ec2'
    static_configs:
      - targets: ['192.168.0.40:8080']  # EC2 App 서버 IP로 교체
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']